### ISSUE TITLE
RBSA Review Checklist

### ISSUE THREAD

**Issue by dchassin** [slacgismo/loadinsight#19]
# normalized_loadshapes.png
- [ ] When the winter peak exceeds the summer peak, the vertical axis of the load shape plots needs to be rescaled to bring the winter peak into view.
- [ ] Some load shapes have simultaneous heating and cooling, which is not possible with the current model.

# total_loadshapes.png
- [ ] Baseload is not correct (it jumps from 0 to something greater than 1.0) in winter, and doesn't show up anywhere else.
- [ ] Some summer load shapes have heating when they shouldn't, or at least not simultaneous with cooling.
